### ISSUE TITLE
iojs v1.3 install failed in osx 10.10 

### ISSUE THREAD

**Issue by mike820324** [dachev/node-cld#12]
Hello, when I'm trying to install the module in iojs version 1.3, the build process failed with the following error message.
```
XX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
../deps/cld/internal/scoreonescriptspan.cc:1145:7: error: non-constant-expression cannot be narrowed from type 'Language' to 'uint16' (aka 'unsigned short') in initializer list
      [-Wc++11-narrowing]
      one_one_lang, UNKNOWN_LANGUAGE, score, 1,
      ^~~~~~~~~~~~
../deps/cld/internal/scoreonescriptspan.cc:1145:7: note: override this message by inserting an explicit cast
      one_one_lang, UNKNOWN_LANGUAGE, score, 1,
      ^~~~~~~~~~~~
      static_cast<uint16>( )
...
...

../deps/cld/internal/scoreonescriptspan.cc:1146:51: note: override this message by inserting an explicit cast
      bytes, 0, scriptspan.ulscript, reliability, reliability
                                                  ^~~~~~~~~~~
                                                  static_cast<uint8>( )
6 errors generated.
```
The reason is that pangyp in iojs will add a "-std=gnu++0x" when compiling the native module. After add a new flag called "-Wno-c++11-narrwoing" in the deps/cld/binding.gyp, the problem solved.

The following is the git diff output:
```diff
diff --git a/deps/cld/binding.gyp b/deps/cld/binding.gyp
index e3d037a..ea614b9 100644
--- a/deps/cld/binding.gyp
+++ b/deps/cld/binding.gyp
@@ -35,7 +35,7 @@
       "defines": [],
       "cflags_cc": ["-w"],
       "xcode_settings": {
-        "OTHER_CFLAGS": ["-w"]
+        "OTHER_CFLAGS": ["-w","-Wno-c++11-narrowing"]
       }
     }
   ]
```
Since it's a small fix, I haven't sent a PR. Sorry bout that :)

**Comment by dachev** [comment]
Thanks @mike820324 I'll deal with it on the weekend.

**Comment by mike820324** [comment]
no problem, glad to help. :)

**Comment by jameswyse** [comment]
:+1: Would be awesome to see iojs support, then I can use it in production!

**Comment by dachev** [comment]
There are further errors that I haven had time to address: https://travis-ci.org/dachev/node-cld/jobs/53461772

**Comment by jameswyse** [comment]
No worries. The master branch is working for me with `iojs@1.6.3`, both locally (osx 10.10), and in production (Docker/Ubuntu 14.04) so I'll stick with that for now :)

**Comment by dachev** [comment]
All kinks have been ironed out. 2.3.0  is published and available.
