### ISSUE TITLE
malformed chunks

### ISSUE THREAD

**Issue by PSeitz** [dachev/node-cld#13]
Hi, I think I found a case where a malformed chunks array is returned. 

var string = 'Das ist ein Test おねがいします';
cld.detect(string, function(err, result) {
    console.log(result);
});

This returns: 
{ reliable: true,
  textBytes: 41,
  languages:
   [ { name: 'Japanese', code: 'ja', percent: 53, score: 3956 },
     { name: 'GERMAN', code: 'de', percent: 42, score: 1445 } ],
  chunks: [ , { name: 'Japanese', code: 'ja', offset: 17, bytes: 21 } ] }

Great module btw!

**Comment by dachev** [comment]
Thanks @PSeitz  I'll take care of it when I return from vacation.

**Comment by dachev** [comment]
Fixed in 2.3.1. Thanks.
