### ISSUE TITLE
Error: 404 status code downloading tarball

### ISSUE THREAD

**Issue by edravis** [dachev/node-cld#15]
### Run command:
`npm i cld`

### Got 
`gyp ERR! stack Error: 404 status code downloading tarball`

### npm suggestion:
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     node-gyp rebuild`

### Environment:
npm v2.0.1
node v2.0.2 (iojs)
Ubuntu 14.04.1

### More info:
First I thought that was iojs, but I try to install into another environment with node v2.0.0 and it works like a charm.

Pastebin with the npm-debug.log:
http://pastebin.com/xrKPsR6k

Any idea? 
Thanks

### Edit:
I downgrade by using `nvm` to 2.0.0 and works like a charm. So I guess is that cld isn't compatible with 2.0.2, could be?

**Comment by dachev** [comment]
I can't reproduce this one. Perhaps it was an intermittent npm glitch. Would you be able to try again?

**Comment by edravis** [comment]
I've tried with the latest version of iojs 2.3.0 and it works.
I've tried with node v2.0.0 and it works.
I've tried with node v2.0.2 and it works.

I guess somehow wasn't working but know it's all clear. 
Thanks for your time anyway :+1:
