### ISSUE TITLE
I try to install cld on smartos but there is an error

### ISSUE THREAD

**Issue by quinvit** [dachev/node-cld#18]
npm install cld
|
> cld@2.4.2 install /root/xxx/node_modules/cld
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/root/xxx/node_modules/cld/build'
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil_shared.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_hint_code.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_impl.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/debug.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/fixunicodevalue.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_entities.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_language.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_ulscript.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/getonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/lang_script.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/offsetmap.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/tote.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/utf8statetable.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_uni_prop_80.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_cjk_compatible.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_delta_bi_32.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_distinct_bi_0.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_16.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_2.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_2.o
  AR(target) Release/obj.target/deps/cld/cld-c.a
  COPY Release/cld-c.a
  CXX(target) Release/obj.target/cld/src/constants.o
  CXX(target) Release/obj.target/cld/src/cld.o
  SOLINK_MODULE(target) Release/obj.target/cld.node
ld: fatal: symbol 'CLD2::kDeltaOcta_obj2' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDeltaOcta2IndSize' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDeltaOcta_obj' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDeltaOctaIndSize' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_deltaoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDistinctOcta_obj2' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDistinctOcta2IndSize' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDistinctOcta_obj' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kDistinctOctaIndSize' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctocta0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_distinctoctachrome.o) type=OBJT);
ld: fatal: symbol 'CLD2::kQuad_obj2' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quad0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quadchrome_16.o) type=OBJT);
ld: fatal: symbol 'CLD2::kQuad_obj' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quad0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quadchrome_16.o) type=OBJT);
ld: fatal: symbol 'CLD2::kQuad_obj2' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quad0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quadchrome_2.o) type=OBJT);
ld: fatal: symbol 'CLD2::kQuad_obj' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quad0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld2_generated_quadchrome_2.o) type=OBJT);
ld: fatal: symbol 'CLD2::kAvgDeltaOctaScore' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld_generated_score_quad_octa_0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld_generated_score_quad_octa_2.o) type=OBJT);
ld: fatal: symbol 'CLD2::kAvgDeltaOctaScoreSize' is multiply-defined:
        (file Release/obj.target/deps/cld/cld-c.a(cld_generated_score_quad_octa_0122.o) type=OBJT; file Release/obj.target/deps/cld/cld-c.a(cld_generated_score_quad_octa_2.o) type=OBJT);
ld: fatal: file processing errors. No output written to Release/obj.target/cld.node
collect2: error: ld returned 1 exit status
  SOLINK_MODULE(target) Release/obj.target/cld.node: Finished
  COPY Release/cld.node
cp: cannot stat ‘Release/obj.target/cld.node’: No such file or directory
cld.target.mk:132: recipe for target 'Release/cld.node' failed
make: *** [Release/cld.node] Error 1
make: Leaving directory '/root/xxx/node_modules/cld/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/xxx/node_modules/cld
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! SunOS 5.11
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "cld"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! cld@2.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cld@2.4.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

Could you please help me figure it out?

**Comment by dachev** [comment]
What OS version are you using? What about node and npm versions?

**Comment by quinvit** [comment]
I used Joyent SmartOS https://docs.joyent.com/public-cloud/containers/infrastructure/images/smartos/managing-a-smartos-instance/finding-your-way-around-in-smartos/the-joyent-linux-to-smartos-cheat-sheet
npm -v
2.11.3
node -v
v0.12.0

Thank you very much.

**Comment by dachev** [comment]
@quinvit I published a new release. Please give it a try and confirm.

**Comment by quinvit** [comment]
It works great now. Thanks for your awesome effort.
