### ISSUE TITLE
elaboration on `score` ?

### ISSUE THREAD

**Issue by tommedema** [dachev/node-cld#23]
When I run

		require('cld').detect('That man is the richest whose pleasure are the cheapest. 能处处寻求快乐的人才是最富有的人。— 梭罗', function(err, result) { console.log(result); });

It returns

	{ reliable: true,
	  textBytes: 114,
	  languages: 
	   [ { name: 'ENGLISH', code: 'en', percent: 49, score: 1517 },
	     { name: 'Chinese', code: 'zh', percent: 49, score: 2066 } ],
	  chunks: 
	   [ { name: 'ENGLISH', code: 'en', offset: 0, bytes: 57 },
	     { name: 'Chinese', code: 'zh', offset: 57, bytes: 61 } ] }

What does this mean? Wich language is more present? English or Chinese? And what does the score mean? Is there a way to normalize the score to a 0 to 100 scale?

**Comment by dachev** [comment]
@tommedema The ```percent``` value represents the language share in the total body of text. I am not sure what ```score ``` represents or how it is computed. There is not documentation on the original project's website: https://code.google.com/p/cld2/
