### ISSUE TITLE
Npm install fail ubuntu 

### ISSUE THREAD

**Issue by sanguinius69** [dachev/node-cld#29]
Hi,
Don't know why but the installation is failing on my server (Ubuntu 14.04 AWS) but working on my mac:
tried with a lot of different node version 
node -v 4.0.0
npm -v 2.14.2
gcc version 4.8.4
currently
here's the error
CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_0122.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_2.o
AR(target) Release/obj.target/deps/cld/cld-c.a
COPY Release/cld-c.a
CXX(target) Release/obj.target/cld/src/constants.o
In file included from ../src/constants.h:4:0,
                 from ../src/constants.cc:3:
../deps/cld/public/compact_lang_det.h:379:28: error: variable or field ‘DumpResultChunkVector’ declared void
 void DumpResultChunkVector(FILE* f, const char* src,
                            ^
../deps/cld/public/compact_lang_det.h:379:28: error: ‘FILE’ was not declared in this scope
../deps/cld/public/compact_lang_det.h:379:34: error: ‘f’ was not declared in this scope
 void DumpResultChunkVector(FILE* f, const char* src,
                                  ^
../deps/cld/public/compact_lang_det.h:379:37: error: expected primary-expression before ‘const’
 void DumpResultChunkVector(FILE* f, const char* src,
                                     ^
../deps/cld/public/compact_lang_det.h:380:45: error: expected primary-expression before ‘*’ token
                            ResultChunkVector* resultchunkvector);
                                             ^
../deps/cld/public/compact_lang_det.h:380:47: error: ‘resultchunkvector’ was not declared in this scope
                            ResultChunkVector* resultchunkvector);
                                               ^
make: *** [Release/obj.target/cld/src/constants.o] Error 1
and after npm error

If you have any clue, we suspect a gcc version but we updated my mac one and can still install.
Thanks a lot for your support

**Comment by sanguinius69** [comment]
My bad, we had a modified version and the line to include the basic library:
#include <stdio.h>
in /deps/cld/public/compact_lang_det.h was missing. I put it back and it is compiling fine.
Thanks & Cheers for the cld !

**Comment by dachev** [comment]
Glad you figured it out.

**Comment by loretoparisi** [comment]
I'm actually getting this error again, details here: https://github.com/dachev/node-cld/issues/19
