### ISSUE TITLE
Duplicate Chunks

### ISSUE THREAD

**Issue by kouga00** [dachev/node-cld#37]
Hello,
in some cases, depends on string, the result contains duplicates:

`{ reliable: true,
     textBytes: 938,
     languages: [ { name: 'ITALIAN', code: 'it', percent: 99, score: 420 } ],
     chunks: [ { name: 'ITALIAN', code: 'it', offset: 0, bytes: 170 },
        { name: 'ITALIAN', code: 'it', offset: 310, bytes: 236 },
        { name: 'ITALIAN', code: 'it', offset: 679, bytes: 257 } ] }`

**Comment by dachev** [comment]
I see 3 non-overlapping chunks in this result so I am not sure what makes them "duplicate".
