### ISSUE TITLE
Automatically remove C source

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [dachev/node-cld#48]
The README says:
> Once the module has been installed, the underlying C source will remain in the deps/cld folder and continue to occupy considerable space. If you are under severe constraints you can delete this folder and reclam >100M

Why can't that directory be removed with postinstall script?

**Comment by loretoparisi** [comment]
This should be as easier as

```json
"scripts": {
    "postinstall" : "rm -rf node_modules/cld/deps"
  }
```

**Comment by dachev** [comment]
This behavior is deliberate: ref #20
