### ISSUE TITLE
Support definition for typescript user.

### ISSUE THREAD

**Issue by webhacking** [dachev/node-cld#59]
This is my own creation. If there is no official position, I will post it myself.

```typescript
interface Language {
  readonly name: string;
  readonly code: string;
  readonly percent: number;
  readonly score: number;
}
interface Chunk {
  readonly name: string;
  readonly code: string;
  readonly offset: number;
  readonly bytes: number;
}
interface Options {
  readonly isHTML: false;
  readonly languageHint: string;
  readonly encodingHint: string;
  readonly tldHint: string;
  readonly httpHint: string;
}
interface DetectLanguage {
  readonly reliable: boolean;
  readonly textBytes: number;
  readonly languages: Language[];
  readonly chunks: Chunk[];
}
export declare module 'cld' {
  declare function detect(text: string, options: Options, callback: (err: string, result: DetectLanguage) => {});
  declare function detect(text: string, callback: (err: string, result: DetectLanguage) => {});
}

```

**Comment by mr-piratman** [comment]
yo mate post it to 
@types/cld

thank you in any case :)

**Comment by shtse8** [comment]
it saves my life!
please post it to `@types/cld`
thanks!

**Comment by dachev** [comment]
@shtse8 I've been out of the JS loop for some time now. Where do I have to put those definitions to make things work for you?

**Comment by shtse8** [comment]
> @shtse8 I've been out of the JS loop for some time now. Where do I have to put those definitions to make things work for you?

It's simple. add the `.d.ts` to the project and reference it in `package.json`.
everything will be done while you publish your package again.

here is the reference:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by dachev** [comment]
v2.8.0

**Comment by dachev** [comment]
Thank you @webhacking  @shtse8 !

**Comment by shtse8** [comment]
Thanks!!! `cld` is the best language detection package I have used.

I can use `cld` in typescript now with strict type supported!
but it seems the definition not accuracy.
it is missing async `detect` definition. only legacy.

please help to change:
from
```ts
export declare module 'cld' {
  declare function detect(text: string, options?: Options, callback?: (err: string, result: DetectLanguage) => {});
  declare function detect(text: string, callback?: (err: string, result: DetectLanguage) => {});
}
```

to
```ts
export declare module 'cld' {
  declare function detect(text: string, options: Options, callback: (err: string, result: DetectLanguage) => void);
  declare function detect(text: string, callback: (err: string, result: DetectLanguage) => void);
  declare function detect(text: string, options: Options) => Promise<DetectLanguage>);
}
```

**Comment by dachev** [comment]
@shtse8 thank you. The new version is 2.8.1.
