### ISSUE TITLE
Installation error :(

### ISSUE THREAD

**Issue by goncer** [dachev/node-cld#63]
Hi, I am having an issue when installing the library in my dockerized Linux image.
`
+ npm install
> cld@2.7.0 install /var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/cld
> node-gyp rebuild
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/.node-gyp/9.11.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
make: Entering directory '/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/cld/build'
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cldutil_shared.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_hint_code.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/compact_lang_det_impl.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/debug.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/fixunicodevalue.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_entities.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_language.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_ulscript.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/getonescriptspan.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/lang_script.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/offsetmap.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/scoreonescriptspan.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/tote.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/utf8statetable.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_uni_prop_80.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_cjk_compatible.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_cjk_delta_bi_32.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/generated_distinct_bi_0.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quad0122.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaocta0122.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_deltaoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctocta0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_distinctoctachrome.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_16.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld2_generated_quadchrome_2.o
CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_0122.o
  CXX(target) Release/obj.target/cld-c/deps/cld/internal/cld_generated_score_quad_octa_2.o
  AR(target) Release/obj.target/deps/cld/cld-c.a
  COPY Release/cld-c.a
  CXX(target) Release/obj.target/cld/src/constants.o
CXX(target) Release/obj.target/cld/src/cld.o

In file included from ../src/cld.cc:12:0:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi.h:2173:49: error: expected ‘)’ before ‘tsFunctionValue’

     ThreadSafeFunction(napi_threadsafe_function tsFunctionValue);

                                                 ^~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi.h:2175:14: error: expected type-specifier before ‘napi_threadsafe_function’

     operator napi_threadsafe_function() const;

              ^~~~~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi.h:2241:25: error: ‘napi_threadsafe_function_call_mode’ has not been declared

                         napi_threadsafe_function_call_mode mode) const;

                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi.h:2248:5: error: ‘napi_threadsafe_function’ does not name a type

     napi_threadsafe_function _tsfn;

     ^~~~~~~~~~~~~~~~~~~~~~~~

In file included from /var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi.h:2426:0,

                 from ../src/cld.cc:12:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::ThreadSafeFunction::ThreadSafeFunction()’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4475:5: error: class ‘Napi::ThreadSafeFunction’ does not have any field named ‘_tsfn’

   : _tsfn() {

     ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: At global scope:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4479:5: error: ISO C++ forbids declaration of ‘ThreadSafeFunction’ with no type [-fpermissive]

     napi_threadsafe_function tsfn)

     ^~~~~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4479:5: error: ‘Napi::ThreadSafeFunction::ThreadSafeFunction’ declared as an ‘inline’ variable

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4479:5: error: ‘int Napi::ThreadSafeFunction::ThreadSafeFunction’ is not a static data member of ‘class Napi::ThreadSafeFunction’

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4479:5: error: ‘napi_threadsafe_function’ was not declared in this scope

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4483:37: error: expected type-specifier before ‘napi_threadsafe_function’

 inline ThreadSafeFunction::operator napi_threadsafe_function() const {

                                     ^~~~~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::BlockingCall() const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4488:32: error: ‘napi_tsfn_blocking’ was not declared in this scope

   return CallInternal(nullptr, napi_tsfn_blocking);

                                ^~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::BlockingCall(Callback) const [with Callback = void*]’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4494:40: error: ‘_tsfn’ was not declared in this scope

   return napi_call_threadsafe_function(_tsfn, data, napi_tsfn_blocking);

                                        ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4494:53: error: ‘napi_tsfn_blocking’ was not declared in this scope

   return napi_call_threadsafe_function(_tsfn, data, napi_tsfn_blocking);

                                                     ^~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4494:71: error: ‘napi_call_threadsafe_function’ was not declared in this scope

   return napi_call_threadsafe_function(_tsfn, data, napi_tsfn_blocking);

                                                                       ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::BlockingCall(Callback) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4500:54: error: ‘napi_tsfn_blocking’ was not declared in this scope

   return CallInternal(new CallbackWrapper(callback), napi_tsfn_blocking);

                                                      ^~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::BlockingCall(DataType*, Callback) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4509:53: error: ‘napi_tsfn_blocking’ was not declared in this scope

   return CallInternal(new CallbackWrapper(wrapper), napi_tsfn_blocking);

                                                     ^~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::NonBlockingCall() const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4513:32: error: ‘napi_tsfn_nonblocking’ was not declared in this scope

   return CallInternal(nullptr, napi_tsfn_nonblocking);

                                ^~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::NonBlockingCall(Callback) const [with Callback = void*]’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4519:40: error: ‘_tsfn’ was not declared in this scope

   return napi_call_threadsafe_function(_tsfn, data, napi_tsfn_nonblocking);

                                        ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4519:53: error: ‘napi_tsfn_nonblocking’ was not declared in this scope

   return napi_call_threadsafe_function(_tsfn, data, napi_tsfn_nonblocking);

                                                     ^~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4519:74: error: ‘napi_call_threadsafe_function’ was not declared in this scope

   return napi_call_threadsafe_function(_tsfn, data, napi_tsfn_nonblocking);

                                                                          ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::NonBlockingCall(Callback) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4525:54: error: ‘napi_tsfn_nonblocking’ was not declared in this scope

   return CallInternal(new CallbackWrapper(callback), napi_tsfn_nonblocking);

                                                      ^~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::NonBlockingCall(DataType*, Callback) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4534:53: error: ‘napi_tsfn_nonblocking’ was not declared in this scope

   return CallInternal(new CallbackWrapper(wrapper), napi_tsfn_nonblocking);

                                                     ^~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘void Napi::ThreadSafeFunction::Ref(napi_env) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4538:7: error: ‘_tsfn’ was not declared in this scope

   if (_tsfn != nullptr) {

       ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4539:65: error: ‘napi_ref_threadsafe_function’ was not declared in this scope

     napi_status status = napi_ref_threadsafe_function(env, _tsfn);

                                                                 ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘void Napi::ThreadSafeFunction::Unref(napi_env) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4545:7: error: ‘_tsfn’ was not declared in this scope

   if (_tsfn != nullptr) {

       ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4546:67: error: ‘napi_unref_threadsafe_function’ was not declared in this scope

     napi_status status = napi_unref_threadsafe_function(env, _tsfn);

                                                                   ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::Acquire() const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4552:43: error: ‘_tsfn’ was not declared in this scope

   return napi_acquire_threadsafe_function(_tsfn);

                                           ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4552:48: error: ‘napi_acquire_threadsafe_function’ was not declared in this scope

   return napi_acquire_threadsafe_function(_tsfn);

                                                ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::Release()’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4556:43: error: ‘_tsfn’ was not declared in this scope

   return napi_release_threadsafe_function(_tsfn, napi_tsfn_release);

                                           ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4556:50: error: ‘napi_tsfn_release’ was not declared in this scope

   return napi_release_threadsafe_function(_tsfn, napi_tsfn_release);

                                                  ^~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4556:67: error: ‘napi_release_threadsafe_function’ was not declared in this scope

   return napi_release_threadsafe_function(_tsfn, napi_tsfn_release);

                                                                   ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::Abort()’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4560:43: error: ‘_tsfn’ was not declared in this scope

   return napi_release_threadsafe_function(_tsfn, napi_tsfn_abort);

                                           ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4560:50: error: ‘napi_tsfn_abort’ was not declared in this scope

   return napi_release_threadsafe_function(_tsfn, napi_tsfn_abort);

                                                  ^~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4560:65: error: ‘napi_release_threadsafe_function’ was not declared in this scope

   return napi_release_threadsafe_function(_tsfn, napi_tsfn_abort);

                                                                 ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘Napi::ThreadSafeFunction::ConvertibleContext Napi::ThreadSafeFunction::GetContext() const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4566:61: error: ‘_tsfn’ was not declared in this scope

   napi_status status = napi_get_threadsafe_function_context(_tsfn, &context);

                                                             ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4566:76: error: ‘napi_get_threadsafe_function_context’ was not declared in this scope

   napi_status status = napi_get_threadsafe_function_context(_tsfn, &context);

                                                                            ^

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::ThreadSafeFunction Napi::ThreadSafeFunction::New(napi_env, const Napi::Function&, const Napi::Object&, ResourceString, size_t, size_t, ContextType*, Finalizer, FinalizerDataType*, napi_finalize)’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4593:53: error: ‘class Napi::ThreadSafeFunction’ has no member named ‘_tsfn’

       finalizeData, wrapper, context, CallJS, &tsfn._tsfn);

                                                     ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: At global scope:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4604:5: error: ‘napi_threadsafe_function_call_mode’ has not been declared

     napi_threadsafe_function_call_mode mode) const {

     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h: In member function ‘napi_status Napi::ThreadSafeFunction::CallInternal(Napi::ThreadSafeFunction::CallbackWrapper*, int) const’:

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4606:7: error: ‘_tsfn’ was not declared in this scope

       _tsfn, callbackWrapper, mode);

       ^~~~~

/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/node-addon-api/napi-inl.h:4606:35: error: ‘napi_call_threadsafe_function’ was not declared in this scope

       _tsfn, callbackWrapper, mode);

                                   ^

cld.target.mk:99: recipe for target 'Release/obj.target/cld/src/cld.o' failed

make: *** [Release/obj.target/cld/src/cld.o] Error 1

make: Leaving directory '/var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/cld/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)

gyp ERR! stack     at ChildProcess.emit (events.js:180:13)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

gyp ERR! System Linux 4.15.0-1058-aws

gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /var/lib/jenkins/workspace/I-back-end-tests-prototype_PR-18/node_modules/cld

gyp ERR! node -v v9.11.2

gyp ERR! node-gyp -v v3.6.2

gyp ERR! not ok 

npm WARN backend-tests@1.0.0 No repository field.

npm WARN The package axios-curlirize is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! cld@2.7.0 install: `node-gyp rebuild`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the cld@2.7.0 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌──────────────────────────────────────────────┐

│           npm update check failed            │

│     Try running with sudo or get access      │

│     to the local update config store via     │

│ sudo chown -R $USER:$(id -gn $USER) /.config │

└──────────────────────────────────────────────┘`

Could you please help me if I missing any dependency or something? 
Thanks!

**Comment by goncer** [comment]
sorry, I tried to format it  a bit, but I completely failed

**Comment by dachev** [comment]
@goncer Can you provide a minimal docker file that demonstrates the issue?

**Comment by goncer** [comment]
Hi @dachev ,
It's running in a company-custom image, I guess that I can not share it with anyone. Without the image, I guess that you can not help me, right?
If so, please close the bug.
Thanks!

**Comment by dachev** [comment]
Please remove everything irrelevant to the failure, including but not limited to proprietary data, and reduce the Docker file to the bare essentials.

**Comment by dachev** [comment]
I can't assist with this one in the complete absence of information about the environment.
