### ISSUE TITLE
Typescript defintions don't match documentation

### ISSUE THREAD

**Issue by fschucht** [dachev/node-cld#71]
We just tried upgrading cld from `2.7.0` to `2.8.1` and it seems like the new typescript declarations don't match the documentation.

Currently we use cld like this:
```js
const detectionResult = await CDL.detect(string);
```

This worked great on version `2.7.0`. However, on version `2.8.1` we get a type error that the options are missing. However, according to the documentation, the function can be called without the options.

**Comment by dachev** [comment]
@fschucht sorry about that. Send a pull request and I'll merge it.

**Comment by dachev** [comment]
v2.8.2
