### ISSUE TITLE
TypeScript types fail with NPM alias

### ISSUE THREAD

**Issue by artursvonda** [dachev/node-cld#82]
When installing forked package under alias (`"cld": "npm:cldpre@^2.9.0"`), the types fail because the types contain hardcoded module name (which forks rename). The forks do this because this original package contains it but instead it should just allow implicit module detection.

In other words,

```
export declare module 'cld' {
  const LANGUAGES: {[name: string]: string};
  const DETECTED_LANGUAGES: string[];
  const ENCODINGS: string[];
  
  declare function detect(text: string, options: Options, callback: (err: string, result: DetectLanguage) => void): void;
  declare function detect(text: string, callback: (err: string, result: DetectLanguage) => void): void;
  declare function detect(text: string, options: Options): Promise<DetectLanguage>;
  declare function detect(text: string): Promise<DetectLanguage>;
}
```
should be replaced with
```
export const LANGUAGES: {[name: string]: string};
export const DETECTED_LANGUAGES: string[];
export const ENCODINGS: string[];

export declare function detect(text: string, options: Options, callback: (err: string, result: DetectLanguage) => void): void;
export declare function detect(text: string, callback: (err: string, result: DetectLanguage) => void): void;
export declare function detect(text: string, options: Options): Promise<DetectLanguage>;
export declare function detect(text: string): Promise<DetectLanguage>;
```

This will allow it to work with any package name and forks won't have to update types at all.

**Comment by dachev** [comment]
@artursvonda how confident are you that this is not going to break existing deployments? Do you consider it pretty safe?

**Comment by artursvonda** [comment]
I don't think it should break any existing code, imports work as they did before. And this is how commonly types are set up, you may check out any types from DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cldr/index.d.ts, for example).

So, without overstating my confidence and reserving rights to be wrong, we should be fairly safe. And we can quickly revert in case things go terribly wrong. if you want even more insurance, we could release this as major. Although I don't believe this to actually be a breaking change.

**Comment by dachev** [comment]
Thank you @artursvonda. I'm a little tied up at the moment so this is going to have to wait until next weekend, but if you need it now send me a pull request and I'll merge it.

**Comment by dachev** [comment]
v2.9.1

**Comment by artursvonda** [comment]
Thanks, @dachev!
